download_collection:
  name: Download Collection
  description: "Downloads your full Discogs collection data to a JSON file."
  fields:
    path:
      name: Path
      description: "The path to save the exported JSON file."
      example: "/config/discogs_collection.json"
